services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: learning
      PGDATA: /var/lib/dev/postgresql/data
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - springboot-net
    restart: unless-stopped

networks:
  springboot-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local